language: python
services:
    - docker
python:
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - TOX_VERSION="tox-2.x"
    - TOX_VERSION="tox-3.x"
install:
    - pip install --constraint "$TOX_VERSION" .
script:
    - tox
    # assure that we fail a build if it contains leftovers
    - git diff --exit-code